Address code review feedback: improve error handling and security
Co-authored-by: jamieshark <5520141+jamieshark@users.noreply.github.com>

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -174,17 +174,19 @@ if [[ -n "$CODESPACES" ]]; then
   # Install fonts for p10k glyphs
   echo "Installing Meslo Nerd Font for p10k glyphs..."
   mkdir -p ~/.local/share/fonts
-  cd ~/.local/share/fonts
+  if ! cd ~/.local/share/fonts; then
+    fail "Failed to change directory to ~/.local/share/fonts"
+  fi
   
   # Download Meslo Nerd Font files
-  curl -fLo "MesloLGS NF Regular.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
-  curl -fLo "MesloLGS NF Bold.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
-  curl -fLo "MesloLGS NF Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
-  curl -fLo "MesloLGS NF Bold Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
+  font_variants=("Regular" "Bold" "Italic" "Bold Italic")
+  for variant in "${font_variants[@]}"; do
+    curl -fLo "MesloLGS NF ${variant}.ttf" "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20${variant// /%20}.ttf"
+  done
   
   # Refresh font cache
   fc-cache -f
-  cd "$DOTFILES_ROOT"
+  cd "$DOTFILES_ROOT" || fail "Failed to return to dotfiles directory"
   success "Meslo Nerd Font installed"
 
   # Set ZSH environment variable before running install
@@ -200,7 +202,7 @@ if [[ -n "$CODESPACES" ]]; then
   # Change default shell to zsh
   if [ "$SHELL" != "$(which zsh)" ]; then
     echo "Changing default shell to zsh..."
-    sudo chsh -s $(which zsh) $(whoami)
+    sudo chsh -s "$(which zsh)" "$(whoami)"
     success "Default shell changed to zsh"
   fi
 
