fix(setup): harden bootstrap and nvm installation

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -38,10 +38,11 @@ setup_gitconfig () {
   local gitconfig_local='git/gitconfig.local.symlink'
   local gitconfig_source='git/gitconfig.local.symlink.example'
   local gitconfig_temp git_authorname='' git_authoremail='' git_config_status
-  local git_credential='cache'
+  local git_credential='' platform_git_credential='cache'
+  local write_git_credential=false
   if [ "$(uname -s)" == "Darwin" ]
   then
-    git_credential='osxkeychain'
+    platform_git_credential='osxkeychain'
   fi
 
   if [ -f "$gitconfig_local" ]
@@ -60,6 +61,17 @@ setup_gitconfig () {
     fi
 
     if git_authoremail=$(git config --file "$gitconfig_local" --get user.email)
+    then
+      :
+    else
+      git_config_status=$?
+      if [ "$git_config_status" -ne 1 ]
+      then
+        fail 'unable to read gitconfig'
+      fi
+    fi
+
+    if git_credential=$(git config --file "$gitconfig_local" --get credential.helper)
     then
       :
     else
@@ -90,12 +102,28 @@ setup_gitconfig () {
     read -r -e git_authoremail
   done
 
+  if [ -z "$git_credential" ] || [ "$git_credential" = 'GIT_CREDENTIAL_HELPER' ]
+  then
+    git_credential="$platform_git_credential"
+    write_git_credential=true
+  fi
   gitconfig_temp=$(mktemp "${gitconfig_local}.XXXXXX")
   if ! cp "$gitconfig_source" "$gitconfig_temp" ||
     ! git config --file "$gitconfig_temp" user.name "$git_authorname" ||
-    ! git config --file "$gitconfig_temp" user.email "$git_authoremail" ||
-    ! git config --file "$gitconfig_temp" credential.helper "$git_credential" ||
-    ! mv "$gitconfig_temp" "$gitconfig_local"
+    ! git config --file "$gitconfig_temp" user.email "$git_authoremail"
+  then
+    rm -f "$gitconfig_temp"
+    fail 'unable to create gitconfig'
+  fi
+
+  if [ "$write_git_credential" = true ] &&
+    ! git config --file "$gitconfig_temp" credential.helper "$git_credential"
+  then
+    rm -f "$gitconfig_temp"
+    fail 'unable to create gitconfig'
+  fi
+
+  if ! mv "$gitconfig_temp" "$gitconfig_local"
   then
     rm -f "$gitconfig_temp"
     fail 'unable to create gitconfig'
@@ -110,13 +138,14 @@ link_file () {
   local overwrite= backup= skip=
   local action=
 
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+  if [[ -e "$dst" || -L "$dst" ]]
   then
 
     if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
     then
 
-      local currentSrc="$(readlink $dst)"
+      local currentSrc
+      currentSrc="$(readlink "$dst")"
 
       if [ "$currentSrc" == "$src" ]
       then
@@ -183,12 +212,15 @@ install_dotfiles () {
   info 'installing dotfiles'
 
   local overwrite_all=${1:-false} backup_all=false skip_all=false
+  local src dst
 
-  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
-  do
+  while IFS= read -r -d '' src; do
     dst="$DOTFILES_DEST/.$(basename "${src%.*}")"
     link_file "$src" "$dst"
-  done
+  done < <(
+    find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' \
+      -not -path '*.git*' -print0
+  )
 }
 
 install_mac_deps () {
